### ISSUE TITLE
Cannot set property 'client' of undefined

### ISSUE THREAD

**Issue by hrecho** [eventOneHQ/apkup#13]
```
TypeError: Cannot set property 'client' of undefined
    at Apkup (c:\_...\node_modules\apkup\dist\index.js:65:21)
```

my gulp task  
```
    var deployData = require('./.deployData.json');	
    const { Apkup } = require('apkup');
    const publisher = Apkup({
        client_email: deployData.clientEmail,
        private_key: deployData.privateKey
    });
...
```
i am 100% sure my auth is correct, as i was using the playup before and its still working   
apkup its not, its giving me this error while creating the publisher

**Comment by nprail** [comment]
This looks like the same issue as #11. `apkup`'s API is a little different than `playup`. 

You basically just have to create a new instance of the `Apkup` class like so:
```js
    var deployData = require('./.deployData.json');	
    const { Apkup } = require('apkup');
    // notice the added `new` 
    const publisher = new Apkup({
        client_email: deployData.clientEmail,
        private_key: deployData.privateKey
    });
...
```

Essentially:
```js
// correct
const apkup = new Apkup({})

// incorrect
const apkup = Apkup({})
```

**Comment by hrecho** [comment]
how do i send you a beer my friend?

**Comment by nprail** [comment]
@hrecho I am glad to help! Considering that you aren't the first person to make that mistake, maybe I should add some documentation that explicitly makes it clear that, while `apkup` is a fork of `playup`, it has changed significantly internally and has a slightly different API. 

If you really want to, I love some coffee :)
https://ko-fi.com/nprail
