### ISSUE TITLE
Add possibility to upload proguard mapping

### ISSUE THREAD

**Issue by Vacxe** [eventOneHQ/apkup#18]
Have a good day. 

Could we extend the functionality and add the possibility to add deobfuscation files
https://developers.google.com/android-publisher/api-ref/edits/deobfuscationfiles/upload

I think that it doesn't take a lot of time. Have a great day mate, and just let me know if I can help with that.

**Comment by nprail** [comment]
I personally don't do deobfuscation so this isn't something I have a need for. I may get around to adding it at some point but if you want to submit a PR, I would be definitely open to it!

**Comment by nprail** [comment]
@Vacxe You can now install this update with `npm install --save-dev apkup@beta`

**Comment by nprail** [comment]
@Vacxe Did you ever have a chance to check if this worked? 

Thanks!

**Comment by Vacxe** [comment]
@nprail yes this functionality is working. No worries.
