### ISSUE TITLE
apkup -h returns a non-zero code: 1

### ISSUE THREAD

**Issue by sarn0ld** [eventOneHQ/apkup#27]
Hey there! 

Thank you for the good work!

I wanted to run apkup -h during my docker build on continous integration. But it returns 1 which indicates an error to CI and let the build fail... 

I think --apk and --key should not be tested when running -h.

**Comment by nprail** [comment]
If you do  `apkup --help`, it will return 0. `-h` isn't actually a valid flag so it returns 1. 

It would probably make sense to add `-h` as an alias of `--help`, though, since that is pretty common 🙂

**Comment by sarn0ld** [comment]
Ah thank you... I just copied the -h from README.md...

Maybe just change the documentation?
