### ISSUE TITLE
AAB support

### ISSUE THREAD

**Issue by nprail** [eventOneHQ/apkup#4]
I just learned about the Android App Bundle (AAB) format. It is a new (2017) Android app format that improves app download sizes. `apkup` should support that file type since it is "the future of Android." 

And that also means that the name `apkup` isn't fully representative of what it actually does anymore...

###
- [ ] Find or build an AAB parser (to extract the package ID and version code from the file)
- [ ] Add AAB option to upload and promote

### Links / Ref
- https://developer.android.com/platform/technology/app-bundle
- https://developers.google.com/android-publisher/api-ref/edits/bundles/upload

**Comment by zdavatz** [comment]
We are also using the `apkup` tool and love it and would love to upload the .aab files via commandline too, as our App is bigger then 100 MB.

**Comment by nprail** [comment]
@zdavatz I'm planning on working on this soon. For the most part, it is completely the same as uploading an APK but there is one snag. The APK upload parses the APK file and pulls the version number and package ID out to use in the upload. A library handles the APK parsing so I do not know how it works. And so far I haven't found an AAB parser library. 

So there are two options. 
1. Require version and package ID to be specified as CLI opts
2. Create an AAB parser

For now, I'm leaning towards 1 because I'm not sure where to start on 2.

**Comment by zdavatz** [comment]
or read 1. from a json file.

**Comment by nprail** [comment]
@zdavatz That is possible as well. At least for the package ID.

**Comment by zdavatz** [comment]
App Version can come from the Manifest File.

**Comment by nprail** [comment]
The AndroidManifest.xml embedded in the aab is encoded. So you'd have to decode it before it's usable. Which is the part that I'm not sure how to do.

**Comment by zdavatz** [comment]
You could use the Path to the source file in the Src dir. I run apkup in my Source Dir.

**Comment by nprail** [comment]
@zdavatz Unfortunately, that won't always work. For example, in a Cordova project, the AndroidManifest.xml is in `platforms/android/app/src/main/AndroidManifest.xml`. And, in my build process at least, the job that uploads the app only has access to the build artifacts and not the source code. 


I think the best option would be to add a CLI option with the version number. Or try to parse the `.aab`.

**Comment by zdavatz** [comment]
Can't you look for the file `AndroidManifest.xml` with a grep or so?

**Comment by zdavatz** [comment]
or ask the user to specify her/his path in a settings file.

**Comment by nprail** [comment]
Searching for it would be inefficient and there is still the case that the `AndroidManifest.xml` isn't even around (e.g. in a deploy job). 

If we are already going to ask for user input, why not just ask for the version number? 

Here is what I'm thinking:
```json
// apkup.json
{
  "key": "./api.json",
  "packageName": "io.event1.app"
}
```

```shell
npx apkup --aab path/to/app.aab --version-code 34
```

**Comment by nprail** [comment]
Actually, after doing a little more docs digging, I determined that we don't need to know the version code. It is only needed for setting the release notes _after_ the AAB has been uploaded. So instead of figuring out the version code manually, we can upload the AAB and then ask the Google API what the version code of that AAB is!

I can do that for APKs too which is nice because that along with the config file will allow me to drop the dependency on `adbkit-apkreader`.

**Comment by zdavatz** [comment]
Great!

**Comment by zdavatz** [comment]
Great!

**Comment by svzi** [comment]
Hi @nprail !

Do you have still plans to implement this change? It would be pretty cool to be able to upload AAB files as well.

Best,
Sven

**Comment by nprail** [comment]
@svzi Yep, I am. I haven't had time to work on `apkup` much lately. Hopefully, at some point soon, I'll make a sprint towards a v2 with AAB support and other features.

**Comment by Ribeiro-Tiago** [comment]
Stumbled upon this from playup, any update on this @nprail ?

I developed an aab parser (https://www.npmjs.com/package/node-aab-parser) inspired by node-apk-parser to extract package name and version (along other things), should make this feature super simple to implement, with something like

```
import { extname } from "path";

(...)

if (extname(inputFile) === ".apk") {
   // use node-apk-parser
} else {
  // use node-aab-parser
}
```

The only downside at the moment is that node-aab-parser requires an absolute path.

Thoughts ?

**Comment by nprail** [comment]
@Ribeiro-Tiago I haven't been able to work on v2 yet. But that AAB parser should allow me to easily implement AAB support quickly without waiting for v2! 

Based on the fact that it requires the Java JDK to be installed, I assume you are wrapping a native tool? 

@svzi @zdavatz Would needing the Java JDK to be installed be acceptable for uploading AABs? 

I think that in the short term, I'll use this parser, but for v2, I will still go with the previous plan of supporting AABs with config files. That way `apkup` won't depend on Java being installed.

**Comment by svzi** [comment]
@nprail When I'm not totally wrong we already need Jaba installed for the Android SDK, so this requirement doesn't look problematic to me. 👍

**Comment by Ribeiro-Tiago** [comment]
@nprail yeah, uses bundletool which is another package I created that's just a wrapper around the binary

But as @svzi says, from my experience (both with react native and ionic) I endup having java installed way before reaching deploy stage

**Comment by nprail** [comment]
@svzi @zdavatz Please try out the new version! I don't have any apps in AAB format at the moment so I can't do a full test.

**Comment by nprail** [comment]
I switched one of my apps to AAB and successfully tested this! I will be releasing 1.3 fully soon.

**Comment by zdavatz** [comment]
Thank you @nprail!

**Comment by chenop** [comment]
Thanks @nprail for supporting aab - this package really make deploy easier on me!
To upload the aab should I use the -apk option?

apkup 
  --key ./key.json 
  --apk /path/to/app-release.apk

**Comment by nprail** [comment]
@chenop Yep, just pass the AAB in with the `--apk` option. For AABs, you will need the Java JDK installed. 

Not exactly intuitive but I'll be making changes in v2 to make it more intuitive and not require Java.

**Comment by andipahlevy** [comment]
Thanks for your work @nprail . You must mention this feature on the docs

**Comment by zdavatz** [comment]
> Thanks for your work @nprail . You must mention this feature on the docs

just send him a Pull request.
