### ISSUE TITLE
Do not define a valid '.' target

### ISSUE THREAD

**Issue by Vacxe** [eventOneHQ/apkup#61]
`Package exports for '/usr/local/lib/node_modules/apkup/node_modules/uuid' do not define a valid '.' target`

This issue begins from ~3 days ago. Any guess?

**Comment by nprail** [comment]
That is very strange, I've not seen this issue before. It seems like it might be an issue with the `uuid` package. 

https://github.com/uuidjs/uuid/issues/466

What version of `uuid` is in your `package-lock.json`?
